name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  deploy:
    runs-on: [ubuntu-latest]

    steps:
      - name: Dockerfile
        run: |
          echo "FROM python:3.9-slim" > Dockerfile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          file: ./Dockerfile
          tags: |
            test/test:latest
          outputs: type=docker,dest=/tmp/test.tar
          
      
